// Curated, general-knowledge guide to common career paths by subject area.
//
// IMPORTANT — this is deliberately NOT course-specific or company-specific
// data. Unlike the rest of this dataset (which is built from real,
// source-cited university/UCAS/Discover Uni figures), there is no reliable,
// verifiable per-course source for "which companies hire graduates of this
// exact course" across all 481 courses — most UK universities simply don't
// publish that. Rather than invent specific employer names against a real
// course (which would misrepresent it as verified data), this module offers
// well-established, general job titles graduates in each broad subject
// area commonly go on to — the kind of guidance a careers adviser would
// give, not a claim about any particular course or university. The UI
// carries an explicit disclaimer alongside it; see CAREER_PATHS_DISCLAIMER.

export const CAREER_PATHS_DISCLAIMER =
  "General guidance on common career paths for this subject area — not specific to this course or university, and not a guarantee of any outcome. For course-specific destinations, see the Career prospects figures above and the university's own careers service."

export const CAREER_PATHS = {
  'Accounting': ['Trainee Accountant', 'Auditor', 'Tax Advisor', 'Management Accountant', 'Financial Analyst'],
  'Accounting and Finance': ['Trainee Accountant', 'Financial Analyst', 'Corporate Finance roles', 'Auditor', 'Investment Analyst'],
  'Acoustical Engineering': ['Acoustic Consultant', 'Audio/Sound Engineer', 'Noise & Vibration Engineer', 'Building Services Engineer', 'Product Development Engineer'],
  'Actuarial Science': ['Trainee Actuary', 'Risk Analyst', 'Pensions Consultant', 'Insurance Underwriter', 'Data Analyst'],
  'Aerospace Engineering': ['Aerospace Engineer', 'Aircraft Design Engineer', 'Systems Engineer', 'Flight Test Engineer', 'Manufacturing Engineer'],
  'Agribusiness': ['Agribusiness Manager', 'Farm Business Consultant', 'Commodity Trader', 'Supply Chain Analyst (agri-food)', 'Agricultural Policy roles'],
  'Agriculture': ['Farm Manager', 'Agronomist', 'Agricultural Consultant', 'Rural Surveyor', 'Agricultural Policy roles'],
  'Animal Science': ['Livestock/Animal Production Specialist', 'Agricultural Consultant', 'Animal Nutrition roles', 'Research Scientist', 'Further study (Veterinary Medicine)'],
  'Archaeology': ['Field Archaeologist', 'Heritage Consultant', 'Museum/Collections Officer', 'Environmental Consultant', 'Further study (Archaeology)'],
  'Archaeology and Heritage Science': ['Conservation Scientist', 'Heritage Consultant', 'Museum/Collections Officer', 'Field Archaeologist', 'Further study (Heritage Science)'],
  'Architecture': ['Architectural Assistant (pre-qualification)', 'Architectural Technologist', 'Urban Designer', 'Sustainability Consultant', 'Further study (Part 2 Architecture)'],
  'Anatomy': ['Research Assistant', 'Anatomical Demonstrator/Technician', 'Biomedical Scientist', 'Medical Science Liaison', 'Further study (Medicine/postgraduate)'],
  'Animal Behaviour': ['Animal Care Specialist / Zookeeper', 'Conservation Officer', 'Animal Behaviour Consultant', 'Research Assistant', 'Veterinary Nurse (with further training)'],
  'Archaeological Science': ['Field Archaeologist', 'Heritage Consultant', 'Museum/Collections Officer', 'Environmental Consultant', 'Forensic Science roles'],
  'Architectural Engineering': ['Structural Engineer', 'Building Services Engineer', 'Architectural Technologist', 'Sustainability Consultant', 'Project Engineer'],
  'Artificial Intelligence': ['Machine Learning Engineer', 'AI Research Scientist', 'Data Scientist', 'Software Engineer', 'NLP/Computer Vision Engineer'],
  'Astrophysics': ['Data Scientist', 'Scientific Software Developer', 'Quantitative Analyst', 'Science Communicator', 'Further study/research (PhD)'],
  'Automotive Engineering': ['Automotive Engineer', 'Powertrain Engineer', 'Vehicle Design Engineer', 'Manufacturing/Production Engineer', 'Test Engineer'],
  'Biochemistry': ['Research Scientist', 'Clinical Biochemist', 'Laboratory Technician', 'Pharmaceutical Scientist', 'Regulatory Affairs Officer'],
  'Biology': ['Research Scientist', 'Laboratory Technician', 'Environmental Consultant', 'Science Teacher', 'Conservation Officer'],
  'Biology and Chemistry': ['Research Scientist', 'Laboratory Technician', 'Pharmaceutical Scientist', 'Science Teacher', 'Quality Control Analyst'],
  'Biomedical Engineering': ['Biomedical Engineer', 'Medical Devices Engineer', 'Clinical Engineer', 'R&D Engineer', 'Regulatory Affairs Specialist'],
  'Biomedical Sciences': ['Biomedical Scientist', 'Clinical Research Associate', 'Laboratory Technician', 'Pharmaceutical Industry roles', 'Further study (Medicine)'],
  'Biotechnology': ['Biotechnologist', 'Research Scientist', 'Bioprocess Engineer', 'Quality Assurance Officer', 'Regulatory Affairs Officer'],
  'Chemical Engineering': ['Process Engineer', 'Chemical Engineer', 'Production Engineer', 'Environmental Engineer', 'Energy/Petrochemical Engineer'],
  'Chemistry': ['Research Chemist', 'Laboratory Analyst', 'Quality Control Chemist', 'Science Teacher', 'Patent Examiner/Attorney (with further training)'],
  'Chinese Studies': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Civil Engineering': ['Civil Engineer', 'Structural Engineer', 'Site Engineer', 'Project Manager', 'Geotechnical Engineer'],
  'Classical Civilisation': ['Museum/Heritage roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Archivist/Records Manager', 'Further study (Classics/Ancient History)'],
  'Classics': ['Museum/Heritage roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Publishing roles', 'Further study (Classics)'],
  'Classical Studies': ['Museum/Heritage roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Archivist/Records Manager', 'Further study (Classics)'],
  'Cognitive Science': ['UX Researcher', 'Data Scientist', 'Research Assistant (Psychology/AI)', 'Human Factors Specialist', 'Further study (Cognitive Science/AI/Psychology)'],
  'Combined Honours': ['Civil Service Fast Stream', 'Management Consultant', 'Publishing roles', 'Policy Researcher', 'Further postgraduate study (varied by subject combination)'],
  'Comparative Literature': ['Publishing roles', 'Translator/Interpreter', 'Teacher (with further training)', 'Journalist', 'Further study (Comparative Literature)'],
  'Computer Science': ['Software Engineer', 'Data Scientist', 'DevOps Engineer', 'Product Manager', 'Cyber Security Analyst', 'Machine Learning Engineer'],
  'Conservation Biology and Ecology': ['Conservation Officer', 'Ecologist', 'Environmental Consultant', 'Wildlife Ranger', 'Countryside/Park Ranger'],
  'Criminology': ['Probation Officer', 'Police roles', 'Policy Researcher', 'Prison/Youth Justice roles', 'Victim Support roles'],
  'Cyber Security': ['Cyber Security Analyst', 'Penetration Tester', 'Security Consultant', 'SOC Analyst', 'Information Security Manager'],
  'Data Science': ['Data Scientist', 'Data Analyst', 'Machine Learning Engineer', 'Business Intelligence Analyst', 'Data Engineer'],
  'Dentistry': ['Dentist (Dental Foundation Training)', 'Dental Researcher', 'Oral & Maxillofacial trainee', 'Public Health Dentistry', 'Practice Ownership (later career)'],
  'Dietetics': ['Dietitian (NHS/private, HCPC registration)', 'Public Health Nutritionist', 'Clinical Nutrition roles', 'Food Industry roles', 'Further study/research (Nutrition)'],
  'Diagnostic Radiography': ['Diagnostic Radiographer', 'MRI/CT Radiographer', 'Sonographer (with further training)', 'Clinical Applications Specialist', 'Imaging Informatics roles'],
  'Discrete Mathematics': ['Data Analyst', 'Software Engineer', 'Cryptographer', 'Operational Researcher', 'Actuarial Analyst'],
  'Earth Sciences': ['Geologist', 'Environmental Consultant', 'Hydrogeologist', 'Mining/Exploration Geologist', 'Geoscience Researcher'],
  'Earth and Planetary Science': ['Geoscience Researcher', 'Environmental Consultant', 'Planetary Scientist (further study)', 'Geophysicist', 'Data Analyst'],
  'Economic History': ['Economic/Policy Researcher', 'Financial Analyst', 'Civil Service Fast Stream', 'Archivist/Heritage roles', 'Further study (Economics/History)'],
  'Economics': ['Economist', 'Financial Analyst', 'Policy Analyst', 'Management Consultant', 'Civil Service Fast Stream'],
  'Education': ['Teacher (with PGCE/further training)', 'Teaching Assistant', 'Education Policy roles', 'Further study (Education)', 'Charity/Youth Work roles'],
  'English Language': ['Copywriter/Editor', 'Speech and Language Therapy (with further training)', 'ESL/EFL Teacher', 'Publishing roles', 'Further study (Linguistics/Education)'],
  'English Language and Linguistics': ['Copywriter/Editor', 'Speech and Language Therapy (with further training)', 'ESL/EFL Teacher', 'Publishing roles', 'Further study (Linguistics/Education)'],
  'English Language and Literature': ['Publishing roles', 'Copywriter/Editor', 'Teacher (with further training)', 'Journalist', 'Arts/Media roles'],
  'English Literature': ['Publishing roles', 'Copywriter/Editor', 'Teacher (with further training)', 'Journalist', 'Arts/Media roles'],
  'Film Studies': ['Film/TV Production roles', 'Script Development/Development Executive', 'Film Journalist/Critic', 'Arts Administrator', 'Further study (Film Studies)'],
  'Theatre and Performance': ['Actor/Performer', 'Director/Producer (theatre)', 'Stage/Production Manager', 'Arts Administrator', 'Drama Teacher (with further training)'],
  'Finance': ['Investment Analyst', 'Financial Analyst', 'Corporate Finance roles', 'Risk Analyst', 'Chartered Accountant (with further training)'],
  'Fine Art': ['Artist/Creative Practitioner', 'Curator/Gallery roles', 'Arts Administrator', 'Art Teacher (with further training)', 'Further study (Fine Art)'],
  'History': ['Civil Service Fast Stream', 'Archivist/Records Manager', 'Museum/Heritage roles', 'Journalist', 'Management Consultant'],
  'International Development': ['International Development/NGO roles', 'Policy Researcher', 'Humanitarian Programme Officer', 'Civil Service Fast Stream', 'Further study (Development Studies)'],
  'International Relations': ['Diplomatic Service/Foreign Office roles', 'International Development/NGO roles', 'Policy Analyst', 'Intelligence Analyst', 'Journalist'],
  'Japanese Studies': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Journalism and Communications': ['Journalist', 'Broadcast Researcher', 'Communications/PR Officer', 'Media Analyst', 'Copywriter/Editor'],
  'Law': ['Trainee Solicitor', 'Barrister (Bar training)', 'Legal Executive', 'Paralegal', 'Compliance Officer'],
  'Business Analytics': ['Data Analyst', 'Business Intelligence Analyst', 'Data Scientist', 'Management Consultant', 'Financial Analyst'],
  'Dental Therapy and Hygiene': ['Dental Therapist (GDC registration)', 'Dental Hygienist', 'Oral Health Educator', 'Community Dental Services roles', 'Practice Management (later career)'],
  'Global Health and Social Medicine': ['Public Health roles', 'Global Health/NGO roles', 'Health Policy Researcher', 'Civil Service/International Organisation roles', 'Further study (Public Health/Medicine)'],
  'Global Health and Social Science': ['Global Health/NGO roles', 'Policy Researcher', 'Public Health roles', 'International Development roles', 'Further study (Global Health/Social Science)'],
  'Liberal Arts': ['Civil Service Fast Stream', 'Management Consultant', 'Publishing roles', 'Policy Researcher', 'Further postgraduate study (varied by pathway)'],
  'Management': ['Management Consultant', 'Graduate Management Trainee', 'HR/People roles', 'Operations Manager', 'Business Analyst'],
  'Media and Communications': ['Media Researcher', 'Communications/PR Officer', 'Social Media Manager', 'Content Producer', 'Marketing roles'],
  'Marketing': ['Marketing Executive', 'Brand Manager (with experience)', 'Digital Marketing Specialist', 'Market Research Analyst', 'PR/Communications roles'],
  'Technology and Innovation': ['Product Manager', 'Innovation Consultant', 'Technology Analyst', 'Business Analyst', 'Graduate Scheme (tech sector)'],
  'Business and Health': ['NHS Management Trainee', 'Healthcare Consultant', 'Health Policy Analyst', 'Pharmaceutical/Life Sciences Business roles', 'Further study (Health Management)'],
  'Communications': ['Communications/PR Officer', 'Media Researcher', 'Broadcast roles', 'Content Producer', 'Marketing roles'],
  'Art and Technology': ['Artist/Creative Practitioner', 'Digital Artist/Technologist', 'Creative Technologist', 'Arts Administrator', 'Further study (Fine Art/Technology)'],
  'Media, Journalism and Culture': ['Journalist', 'Media Researcher', 'Communications/PR Officer', 'Content Producer', 'Arts/Cultural roles'],
  'Midwifery': ['Midwife (NHS/private practice)', 'Maternity Support Worker', 'Public Health roles', 'Clinical Researcher', 'Health Visitor (with further training)'],
  'Modern Chinese': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Modern Languages': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'Icelandic': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'French': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'German': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'Dutch': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'Italian': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'Russian Studies': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Spanish and Latin American Studies': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Hebrew and Jewish Studies': ['Teacher (with further training)', 'Charity/NGO roles', 'Publishing/Journalism/Translation roles', 'Civil Service Fast Stream', 'Further study (Languages/Area Studies)'],
  'Ancient Languages': ['Museum/Heritage roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Publishing/Translation roles', 'Further study (Ancient Languages/Classics)'],
  'Arts and Sciences': ['Civil Service Fast Stream', 'Management Consultant', 'Policy Researcher', 'Data Analyst', 'Further postgraduate study (varied by pathway)'],
  'Music': ['Performing Musician', 'Music Teacher', 'Composer/Arranger', 'Music Producer/Sound Engineer', 'Arts Administrator'],
  'Nursing': ['Registered Nurse (NHS/private)', 'Specialist Nurse (with further training)', 'Health Visitor (with further training)', 'Clinical Researcher', 'NHS Management (later career)'],
  'Occupational Therapy': ['Occupational Therapist (NHS/private)', 'Rehabilitation Specialist', 'Community Health roles', 'Clinical Researcher', 'Paediatric/Mental Health OT roles'],
  'Philosophy': ['Policy Researcher', 'Management Consultant', 'Civil Service Fast Stream', 'Journalist', 'Further study (Law/Academia)'],
  'Philosophy, Politics and Economics': ['Management Consultant', 'Civil Service Fast Stream', 'Policy Analyst', 'Financial Analyst', 'Journalist'],
  'Politics': ['Policy Analyst', 'Civil Service Fast Stream', 'Political Researcher/Caseworker', 'Public Affairs/Lobbying roles', 'Journalist'],
  'Politics and International Relations': ['Policy Analyst', 'Civil Service Fast Stream', 'Diplomatic Service/Foreign Office roles', 'Political Researcher/Caseworker', 'Journalist'],
  'Radiotherapy and Oncology': ['Therapeutic Radiographer', 'Oncology Support roles', 'Clinical Technologist', 'Imaging Informatics roles', 'Clinical Researcher'],
  'Social Anthropology': ['Research Assistant', 'International Development/NGO roles', 'Policy Researcher', 'Market Research Analyst', 'Museum/Heritage roles'],
  'Social Policy': ['Policy Analyst', 'Civil Service Fast Stream', 'Charity/NGO roles', 'Social Researcher', 'Public Sector Management'],
  'Social Sciences': ['Policy Researcher', 'Civil Service Fast Stream', 'Social Researcher', 'Charity/NGO roles', 'Management Consultant'],
  'Social Work': ['Social Worker (with Social Work England registration)', 'Child Protection/Safeguarding roles', 'Family Support Worker', 'Charity/NGO roles', 'Further study (postgraduate Social Work/specialist practice)'],
  'Sociology': ['Policy Researcher', 'Social Researcher', 'HR/People roles', 'Charity/NGO roles', 'Market Research Analyst'],
  'Spanish': ['Translator/Interpreter', 'International Business roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Further study (Languages)'],
  'Theology and Religious Studies': ['Civil Service Fast Stream', 'Teacher (with further training)', 'Charity/NGO roles', 'Chaplaincy/Pastoral roles', 'Further study (Theology)'],
  'Translation': ['Translator', 'Interpreter', 'Localization Specialist', 'Publishing roles', 'International Organisation roles'],
  'Town & Country Planning': ['Town Planner', 'Urban Designer', 'Planning Officer', 'Sustainability Consultant', 'Surveyor'],
  'Urban Planning': ['Town Planner', 'Urban Designer', 'Planning Officer', 'Sustainability Consultant', 'Surveyor'],
  'Urban Studies': ['Town Planner', 'Urban Researcher', 'Policy Researcher', 'Sustainability Consultant', 'Local Government roles'],
  'Visual Arts and Film': ['Film/TV Production roles', 'Artist/Creative Practitioner', 'Curator/Gallery roles', 'Arts Administrator', 'Further study (Fine Art/Film)'],
  'Welsh': ['Welsh-medium Teacher', 'Broadcasting/Media roles (S4C, BBC Cymru)', 'Translator (Welsh/English)', 'Civil Service (Wales)', 'Arts/Heritage roles'],
  'Youth, Society and Sustainable Futures': ['Youth Worker', 'Charity/NGO roles', 'Community Development Officer', 'Policy Researcher', 'Further study (Education/Social Policy)'],
  'Audiology': ['Audiologist (NHS/private, RCCP/HCPC registration)', 'Hearing Aid Dispenser', 'Clinical Scientist (Audiology)', 'Research Assistant', 'Further study (Audiology/Clinical Science)'],
  'Human Neuroscience': ['Research Scientist', 'Clinical Research Associate', 'Assistant Psychologist', 'Pharmaceutical Scientist', 'Further study (Medicine/Neuroscience PhD)'],
  'Global Humanitarian Studies': ['Humanitarian Programme Officer', 'International Development/NGO roles', 'Disaster Risk Reduction roles', 'Policy Researcher', 'International Organisation roles (UN/Red Cross)'],
  'Population Health Sciences': ['Public Health roles', 'Health Policy Researcher', 'Epidemiology roles (with further training)', 'NHS Analyst', 'Further study (Public Health/Epidemiology)'],
  'Crime and Security Science': ['Police roles', 'Intelligence Analyst', 'Security Consultant', 'Civil Service/Home Office roles', 'Fraud/Risk Analyst'],
  'Electrical and Electronic Engineering': ['Electrical Engineer', 'Electronics Engineer', 'Systems Engineer', 'Power Engineer', 'Embedded Software Engineer'],
  'Engineering': ['Graduate Engineer', 'Project Engineer', 'Design Engineer', 'Manufacturing Engineer', 'Consulting Engineer'],
  'Engineering Mathematics': ['Data Scientist', 'Systems Engineer', 'Quantitative Analyst', 'Software Engineer', 'Operational Researcher'],
  'Environmental Science': ['Environmental Consultant', 'Sustainability Officer', 'Conservation Officer', 'Environmental Scientist (regulatory bodies)', 'Climate/Energy Analyst'],
  'Evolutionary Biology': ['Research Scientist', 'Conservation Biologist', 'Science Communicator', 'Laboratory Technician', 'Further study (PhD/academia)'],
  'Food Science': ['Food Technologist', 'Quality Assurance Officer', 'Product Development Scientist', 'Regulatory Affairs Officer', 'Nutritionist (with further training)'],
  'Genetics': ['Research Scientist', 'Clinical Scientist', 'Laboratory Technician', 'Bioinformatician', 'Genetic Counsellor (with further training)'],
  'Geography': ['Environmental Consultant', 'Urban/Town Planner', 'GIS Analyst', 'Sustainability Officer', 'Market Research Analyst'],
  'Human Geography': ['Urban/Town Planner', 'GIS Analyst', 'Policy Researcher', 'Sustainability Officer', 'International Development/NGO roles'],
  'Geology & Earth Sciences': ['Geologist', 'Environmental Consultant', 'Mining/Exploration Geologist', 'Hydrogeologist', 'Geotechnical roles'],
  'Human Sciences': ['Public Health roles', 'Policy Analyst', 'Research Assistant', 'NGO/Development Worker', 'Further study (Medicine/Anthropology)'],
  'Infection and Immunity': ['Research Scientist', 'Clinical Research Associate', 'Biomedical Scientist', 'Public Health roles', 'Pharmaceutical Scientist'],
  'Landscape Architecture': ['Landscape Architect', 'Urban Designer', 'Environmental Planner', 'Landscape Consultant', 'Heritage/Conservation roles'],
  'Manufacturing and Mechanical Engineering': ['Manufacturing Engineer', 'Mechanical Engineer', 'Production Engineer', 'Quality Engineer', 'Process Improvement Engineer'],
  'Marine Biology': ['Marine Biologist', 'Conservation Officer', 'Research Assistant', 'Environmental Consultant', 'Aquarist'],
  'Marine Zoology': ['Marine Biologist', 'Conservation Officer', 'Research Assistant', 'Environmental Consultant', 'Aquarist'],
  'Materials Science': ['Materials Engineer', 'Research Scientist', 'Quality Engineer', 'Process Engineer', 'R&D roles in manufacturing'],
  'Mathematics': ['Data Analyst', 'Actuarial Analyst', 'Operational Researcher', 'Software Engineer', 'Quantitative Analyst'],
  'Mathematics & Statistics': ['Data Scientist', 'Statistician', 'Actuarial Analyst', 'Quantitative Analyst', 'Operational Researcher'],
  'Mathematics and Physics': ['Data Scientist', 'Quantitative Analyst', 'Research Scientist', 'Software Engineer', 'Graduate Engineer'],
  'Mathematics, Operational Research, Statistics and Economics': ['Operational Researcher', 'Data Analyst', 'Economist', 'Actuarial Analyst', 'Business Analyst'],
  'Mechanical Engineering': ['Mechanical Engineer', 'Design Engineer', 'Manufacturing Engineer', 'Project Engineer', 'Maintenance/Reliability Engineer'],
  'Medical Engineering': ['Biomedical/Medical Devices Engineer', 'Clinical Engineer', 'R&D Engineer', 'Regulatory Affairs Specialist', 'Rehabilitation Engineer'],
  'Medical Physics': ['Medical Physicist (with further training)', 'Clinical Technologist', 'Radiation Protection Adviser', 'Imaging Physicist', 'Research Scientist'],
  'Medicinal Chemistry': ['Medicinal/Pharmaceutical Chemist', 'Drug Discovery Scientist', 'Quality Control Chemist', 'Regulatory Affairs Officer', 'Research Scientist'],
  'Medicine': ['Doctor (Foundation Programme)', 'Specialty Trainee Doctor', 'Medical Researcher', 'Public Health Doctor', 'NHS Clinical Leadership (later career)'],
  'Microbiology': ['Microbiologist', 'Research Scientist', 'Clinical/Public Health Laboratory Scientist', 'Quality Control Analyst', 'Pharmaceutical Scientist'],
  'Molecular Cell Biology': ['Research Scientist', 'Laboratory Technician', 'Biomedical Scientist', 'Pharmaceutical Scientist', 'Further study (PhD)'],
  'Natural Sciences': ['Research Scientist', 'Laboratory roles (biology/chemistry/physics)', 'Science Teacher', 'Data Analyst', 'Science Communicator'],
  'Neuroscience': ['Research Scientist', 'Clinical Research Associate', 'Assistant Psychologist', 'Pharmaceutical Scientist', 'Further study (Medicine/PhD)'],
  'Nutrition': ['Nutritionist', 'Dietitian (with further training)', 'Public Health roles', 'Food Industry Scientist', 'Health/Wellness Consultant'],
  'Nutritional Sciences': ['Nutritionist', 'Dietitian (with further training)', 'Public Health roles', 'Food Industry Scientist', 'Health/Wellness Consultant'],
  'Oceanography': ['Oceanographer', 'Environmental Consultant', 'Marine Data Analyst', 'Research Scientist', 'Hydrographic Surveyor'],
  'Optometry': ['Optometrist', 'Dispensing Optician', 'Ophthalmic roles', 'Clinical Researcher', 'Practice Management (later career)'],
  'Pharmacology': ['Pharmacologist', 'Research Scientist', 'Drug Safety/Pharmacovigilance Officer', 'Regulatory Affairs Officer', 'Medical Science Liaison'],
  'Pharmacy': ['Pharmacist (community/hospital)', 'Clinical Pharmacist', 'Pharmaceutical Industry roles', 'Regulatory Affairs', 'Academic Pharmacy'],
  'Physics': ['Research Scientist', 'Data Analyst', 'Graduate Engineer', 'Science Teacher', 'Quantitative Analyst'],
  'Physics and Philosophy': ['Data Analyst', 'Policy Researcher', 'Science Writer/Communicator', 'Research Scientist', 'Management Consultant'],
  'Physiotherapy': ['Physiotherapist (NHS/private practice)', 'Sports Rehabilitation Specialist', 'Musculoskeletal Practitioner', 'Clinical Researcher', 'Community Health roles'],
  'Psychology': ['Assistant Psychologist', 'HR/People roles', 'Market Researcher', 'Mental Health Support Worker', 'Further study (Clinical/Educational Psychology)'],
  'Robotic Engineering': ['Robotics Engineer', 'Automation Engineer', 'Control Systems Engineer', 'Software/Firmware Engineer', 'R&D Engineer'],
  'Ship Science': ['Naval Architect', 'Marine Engineer', 'Ship Surveyor', 'Offshore Engineer', 'Project Engineer (marine industry)'],
  'Spanish, Portuguese and Latin American Studies': ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)'],
  'Speech and Language Therapy': ['Speech and Language Therapist (HCPC/RCSLT registration)', 'NHS Clinical roles', 'Community Health roles', 'Clinical Researcher', 'Private Practice (later career)'],
  'Sport and Exercise Medical Sciences': ['Sports Scientist', 'Clinical Exercise Physiologist (with further training)', 'Sports Rehabilitation Specialist', 'Performance Analyst', 'Further study (Sports Medicine/Physiotherapy)'],
  'Sport and Exercise Science': ['Sports Scientist', 'Strength & Conditioning Coach', 'Sports Therapist (with further training)', 'PE Teacher', 'Performance Analyst'],
  'Statistics': ['Statistician', 'Data Scientist', 'Actuarial Analyst', 'Market Research Analyst', 'Operational Researcher'],
  'Theoretical Physics': ['Research Scientist', 'Quantitative Analyst', 'Data Scientist', 'Software Engineer', 'Further study/academia (PhD)'],
  'War Studies': ['Intelligence Analyst', 'Civil Service/Defence roles', 'International Organisation roles (UN/NATO/EU)', 'Security/Risk Consultant', 'Journalist'],
  'Veterinary Biosciences': ['Research Scientist', 'Laboratory Technician', 'Animal Health/Welfare roles', 'Pharmaceutical Scientist', 'Further study (Veterinary Medicine)'],
  'Veterinary Medicine': ['Veterinary Surgeon', 'Veterinary Researcher', 'Animal Welfare/Charity roles', 'Veterinary Public Health', 'Practice Ownership (later career)'],
  'Zoology': ['Conservation Officer', 'Animal Care Specialist / Zookeeper', 'Research Scientist', 'Wildlife Ranger', 'Environmental Consultant'],
}

// Keyword-based fallback for any subjectArea not explicitly listed above
// (e.g. a future data-expansion pass adds a new category before this file
// is updated) — matched against broad, recognisable subject keywords so a
// reasonable general answer is still shown rather than nothing.
const FALLBACK_KEYWORDS = [
  ['engineer', ['Graduate Engineer', 'Design Engineer', 'Project Engineer', 'Manufacturing Engineer', 'Consulting Engineer']],
  ['comput', ['Software Engineer', 'Data Scientist', 'IT Consultant', 'Systems Analyst', 'DevOps Engineer']],
  ['data', ['Data Analyst', 'Data Scientist', 'Business Intelligence Analyst', 'Data Engineer', 'Quantitative Analyst']],
  ['math', ['Data Analyst', 'Actuarial Analyst', 'Operational Researcher', 'Quantitative Analyst', 'Software Engineer']],
  ['stat', ['Statistician', 'Data Scientist', 'Actuarial Analyst', 'Market Research Analyst', 'Operational Researcher']],
  ['physic', ['Research Scientist', 'Data Analyst', 'Graduate Engineer', 'Science Teacher', 'Quantitative Analyst']],
  ['chem', ['Research Chemist', 'Laboratory Analyst', 'Quality Control Chemist', 'Science Teacher', 'Regulatory Affairs Officer']],
  ['biolog', ['Research Scientist', 'Laboratory Technician', 'Environmental Consultant', 'Science Teacher', 'Conservation Officer']],
  ['medic', ['Doctor/Clinician (with further training)', 'Medical Researcher', 'Public Health roles', 'NHS roles', 'Further postgraduate study']],
  ['environment', ['Environmental Consultant', 'Sustainability Officer', 'Conservation Officer', 'Environmental Scientist', 'Climate/Energy Analyst']],
  ['psycholog', ['Assistant Psychologist', 'HR/People roles', 'Market Researcher', 'Mental Health Support Worker', 'Further study (Clinical Psychology)']],
  ['law', ['Trainee Solicitor', 'Barrister (Bar training)', 'Legal Executive', 'Paralegal', 'Compliance Officer']],
  ['econ', ['Economist', 'Financial Analyst', 'Policy Analyst', 'Management Consultant', 'Civil Service Fast Stream']],
  ['financ', ['Investment Analyst', 'Financial Analyst', 'Corporate Finance roles', 'Risk Analyst', 'Chartered Accountant (with further training)']],
  ['manage', ['Management Consultant', 'Graduate Management Trainee', 'HR/People roles', 'Operations Manager', 'Business Analyst']],
  ['polit', ['Policy Analyst', 'Civil Service Fast Stream', 'Political Researcher/Caseworker', 'Public Affairs/Lobbying roles', 'Journalist']],
  ['international relations', ['Diplomatic Service/Foreign Office roles', 'International Development/NGO roles', 'Policy Analyst', 'Intelligence Analyst', 'Journalist']],
  ['sociolog', ['Policy Researcher', 'Social Researcher', 'HR/People roles', 'Charity/NGO roles', 'Market Research Analyst']],
  ['anthropolog', ['Research Assistant', 'International Development/NGO roles', 'Policy Researcher', 'Market Research Analyst', 'Museum/Heritage roles']],
  ['philosoph', ['Policy Researcher', 'Management Consultant', 'Civil Service Fast Stream', 'Journalist', 'Further study (Law/Academia)']],
  ['histor', ['Civil Service Fast Stream', 'Archivist/Records Manager', 'Museum/Heritage roles', 'Journalist', 'Management Consultant']],
  ['social polic', ['Policy Analyst', 'Civil Service Fast Stream', 'Charity/NGO roles', 'Social Researcher', 'Public Sector Management']],
  ['account', ['Trainee Accountant', 'Auditor', 'Tax Advisor', 'Management Accountant', 'Financial Analyst']],
  ['urban plan', ['Town Planner', 'Urban Designer', 'Planning Officer', 'Sustainability Consultant', 'Surveyor']],
  ['town plan', ['Town Planner', 'Urban Designer', 'Planning Officer', 'Sustainability Consultant', 'Surveyor']],
  ['linguist', ['Copywriter/Editor', 'Speech and Language Therapy (with further training)', 'ESL/EFL Teacher', 'Publishing roles', 'Further study (Linguistics/Education)']],
  ['translat', ['Translator', 'Interpreter', 'Localization Specialist', 'Publishing roles', 'International Organisation roles']],
  ['music', ['Performing Musician', 'Music Teacher', 'Composer/Arranger', 'Music Producer/Sound Engineer', 'Arts Administrator']],
  ['archaeolog', ['Field Archaeologist', 'Heritage Consultant', 'Museum/Collections Officer', 'Environmental Consultant', 'Further study (Archaeology)']],
  ['criminolog', ['Probation Officer', 'Police roles', 'Policy Researcher', 'Prison/Youth Justice roles', 'Victim Support roles']],
  ['educat', ['Teacher (with PGCE/further training)', 'Teaching Assistant', 'Education Policy roles', 'Further study (Education)', 'Charity/Youth Work roles']],
  ['midwif', ['Midwife (NHS/private practice)', 'Maternity Support Worker', 'Public Health roles', 'Clinical Researcher', 'Health Visitor (with further training)']],
  ['nursing', ['Registered Nurse (NHS/private)', 'Specialist Nurse (with further training)', 'Health Visitor (with further training)', 'Clinical Researcher', 'NHS Management (later career)']],
  ['occupational therap', ['Occupational Therapist (NHS/private)', 'Rehabilitation Specialist', 'Community Health roles', 'Clinical Researcher', 'Paediatric/Mental Health OT roles']],
  ['radiotherap', ['Therapeutic Radiographer', 'Oncology Support roles', 'Clinical Technologist', 'Imaging Informatics roles', 'Clinical Researcher']],
  ['architect', ['Architectural Assistant (pre-qualification)', 'Architectural Technologist', 'Urban Designer', 'Sustainability Consultant', 'Further study (Part 2 Architecture)']],
  ['journalis', ['Journalist', 'Broadcast Researcher', 'Communications/PR Officer', 'Media Analyst', 'Copywriter/Editor']],
  ['media', ['Media Researcher', 'Communications/PR Officer', 'Social Media Manager', 'Content Producer', 'Marketing roles']],
  ['classic', ['Museum/Heritage roles', 'Teacher (with further training)', 'Civil Service Fast Stream', 'Archivist/Records Manager', 'Further study (Classics)']],
  ['theolog', ['Civil Service Fast Stream', 'Teacher (with further training)', 'Charity/NGO roles', 'Chaplaincy/Pastoral roles', 'Further study (Theology)']],
  ['chinese', ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)']],
  ['japanese', ['Translator/Interpreter', 'International Business roles', 'Diplomatic Service/Foreign Office roles', 'Teacher (with further training)', 'Further study (Languages/Area Studies)']],
  ['visual arts', ['Film/TV Production roles', 'Artist/Creative Practitioner', 'Curator/Gallery roles', 'Arts Administrator', 'Further study (Fine Art/Film)']],
  ['liberal arts', ['Civil Service Fast Stream', 'Management Consultant', 'Publishing roles', 'Policy Researcher', 'Further postgraduate study (varied by pathway)']],
  ['social scien', ['Policy Researcher', 'Civil Service Fast Stream', 'Social Researcher', 'Charity/NGO roles', 'Management Consultant']],
  ['planetary', ['Geoscience Researcher', 'Environmental Consultant', 'Planetary Scientist (further study)', 'Geophysicist', 'Data Analyst']],
  ['film', ['Film/TV Production roles', 'Script Development/Development Executive', 'Film Journalist/Critic', 'Arts Administrator', 'Further study (Film Studies)']],
  ['war studies', ['Intelligence Analyst', 'Civil Service/Defence roles', 'International Organisation roles (UN/NATO/EU)', 'Security/Risk Consultant', 'Journalist']],
  ['marketing', ['Marketing Executive', 'Brand Manager (with experience)', 'Digital Marketing Specialist', 'Market Research Analyst', 'PR/Communications roles']],
  ['development', ['International Development/NGO roles', 'Policy Researcher', 'Humanitarian Programme Officer', 'Civil Service Fast Stream', 'Further study (Development Studies)']],
  ['dental', ['Dental Therapist/Hygienist (GDC registration)', 'Oral Health Educator', 'Community Dental Services roles', 'Dentistry (with further training)', 'Practice Management (later career)']],
  ['global health', ['Public Health roles', 'Global Health/NGO roles', 'Health Policy Researcher', 'International Organisation roles', 'Further study (Public Health)']],
  ['business analytic', ['Data Analyst', 'Business Intelligence Analyst', 'Data Scientist', 'Management Consultant', 'Financial Analyst']],
  ['comparative literature', ['Publishing roles', 'Translator/Interpreter', 'Teacher (with further training)', 'Journalist', 'Further study (Comparative Literature)']],
]

const DEFAULT_CAREER_PATHS = [
  'Graduate scheme roles related to this subject',
  'Research or laboratory roles',
  'Roles in industry, the public sector, or academia',
  'Further postgraduate study (MSc/PhD)',
]

export function getCareerPaths(subjectArea) {
  if (CAREER_PATHS[subjectArea]) return CAREER_PATHS[subjectArea]
  const lower = (subjectArea || '').toLowerCase()
  for (const [keyword, paths] of FALLBACK_KEYWORDS) {
    if (lower.includes(keyword)) return paths
  }
  return DEFAULT_CAREER_PATHS
}
